name: Build release zip

on:
  workflow_dispatch

env:
  SLUG:disable-password-changed-email

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@stable
      with:
        retention-days: 1 # Optional; defaults to 5